language: cpp
compiler:
  - gcc
env:
  global:
    - GCC_VERSION="4.6"
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake
install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "g++-${GCC_VERSION}"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
script:
  - cmake --version
  - cmake . -G"Unix Makefiles" -DCMAKE_CXX_COMPILER=$(which $CXX)
  - make
  - make test

